// Code generated by protoc-gen-go.
// source: todo.proto
// DO NOT EDIT!

/*
Package todo is a generated protocol buffer package.

It is generated from these files:
	todo.proto

It has these top-level messages:
	TodoItem
*/
package todo

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TodoItem struct {
	Msg  string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
	Done bool   `protobuf:"varint,2,opt,name=done" json:"done,omitempty"`
}

func (m *TodoItem) Reset()                    { *m = TodoItem{} }
func (m *TodoItem) String() string            { return proto.CompactTextString(m) }
func (*TodoItem) ProtoMessage()               {}
func (*TodoItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TodoItem) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *TodoItem) GetDone() bool {
	if m != nil {
		return m.Done
	}
	return false
}

func init() {
	proto.RegisterType((*TodoItem)(nil), "TodoItem")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Database service

type DatabaseClient interface {
	CreateTodoItem(ctx context.Context, in *TodoItem, opts ...grpc.CallOption) (*TodoItem, error)
}

type databaseClient struct {
	cc *grpc.ClientConn
}

func NewDatabaseClient(cc *grpc.ClientConn) DatabaseClient {
	return &databaseClient{cc}
}

func (c *databaseClient) CreateTodoItem(ctx context.Context, in *TodoItem, opts ...grpc.CallOption) (*TodoItem, error) {
	out := new(TodoItem)
	err := grpc.Invoke(ctx, "/Database/CreateTodoItem", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Database service

type DatabaseServer interface {
	CreateTodoItem(context.Context, *TodoItem) (*TodoItem, error)
}

func RegisterDatabaseServer(s *grpc.Server, srv DatabaseServer) {
	s.RegisterService(&_Database_serviceDesc, srv)
}

func _Database_CreateTodoItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TodoItem)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServer).CreateTodoItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Database/CreateTodoItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServer).CreateTodoItem(ctx, req.(*TodoItem))
	}
	return interceptor(ctx, in, info, handler)
}

var _Database_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Database",
	HandlerType: (*DatabaseServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTodoItem",
			Handler:    _Database_CreateTodoItem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "todo.proto",
}

func init() { proto.RegisterFile("todo.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 118 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0xc9, 0x4f, 0xc9,
	0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x32, 0xe0, 0xe2, 0x08, 0xc9, 0x4f, 0xc9, 0xf7, 0x2c,
	0x49, 0xcd, 0x15, 0x12, 0xe0, 0x62, 0xce, 0x2d, 0x4e, 0x97, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c,
	0x02, 0x31, 0x85, 0x84, 0xb8, 0x58, 0x52, 0xf2, 0xf3, 0x52, 0x25, 0x98, 0x14, 0x18, 0x35, 0x38,
	0x82, 0xc0, 0x6c, 0x23, 0x13, 0x2e, 0x0e, 0x97, 0xc4, 0x92, 0xc4, 0xa4, 0xc4, 0xe2, 0x54, 0x21,
	0x0d, 0x2e, 0x3e, 0xe7, 0xa2, 0xd4, 0xc4, 0x92, 0x54, 0xb8, 0x19, 0x9c, 0x7a, 0x30, 0xa6, 0x14,
	0x82, 0xa9, 0xc4, 0x90, 0xc4, 0x06, 0xb6, 0xce, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xee, 0x7a,
	0xd2, 0x81, 0x7c, 0x00, 0x00, 0x00,
}
