<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: todo.proto

namespace GPBMetadata;

class Todo
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a710a0a746f646f2e70726f746f22250a08546f646f4974656d120b0a03" .
            "6d7367180120012809120c0a04646f6e6518022001280832340a08446174" .
            "616261736512280a0e437265617465546f646f4974656d12092e546f646f" .
            "4974656d1a092e546f646f4974656d2200620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

